// Mocks generated by Mockito 5.4.6 from annotations
// in yuruk/test/domain/usecases/stop_run_session_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yuruk/domain/entities/run_session.dart' as _i4;
import 'package:yuruk/domain/repositories/run_session_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RunSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunSessionRepository extends _i1.Mock
    implements _i2.RunSessionRepository {
  MockRunSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSession(_i4.RunSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.RunSession?> getSessionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionById, [id]),
            returnValue: _i3.Future<_i4.RunSession?>.value(),
          )
          as _i3.Future<_i4.RunSession?>);

  @override
  _i3.Future<List<_i4.RunSession>> getAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSessions, []),
            returnValue: _i3.Future<List<_i4.RunSession>>.value(
              <_i4.RunSession>[],
            ),
          )
          as _i3.Future<List<_i4.RunSession>>);

  @override
  _i3.Future<void> deleteSession(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
